### ISSUE TITLE
Setting option to the server

### ISSUE THREAD

**Issue by waghanza** [RobertoPrevato/BlackSheep#16]
Hi @RobertoPrevato,

Following https://github.com/RobertoPrevato/BlackSheep/wiki/Automatic-reload, I use 
```python
from blacksheep.server import Application, ServerOptions
```

to set **host** and **port** for the server

but on `0.1.4` I have 
```python
ImportError: cannot import name 'ServerOptions' from 'blacksheep.server' (/usr/local/lib64/python3.7/site-packages/blacksheep/server/__init__.py)
```

Regards,

**Comment by waghanza** [comment]
I see that the `cython` source for **options** has been removed on #15, I have the switch to `gunicorn` (`uvicorn` based)
```python
gunicorn --log-level warning --bind 0.0.0.0:3000 --reuse-port --workers $(nproc) --worker-class uvicorn.workers.UvicornWorker server:app
```

**Comment by RobertoPrevato** [comment]
Exactly! Thank You!
