### ISSUE TITLE
default example not work on Linux Ubyuntu.

### ISSUE THREAD

**Issue by catafest** [RobertoPrevato/BlackSheep#33]
I try to run on ubuntu 
```
Successfully built blacksheep
Installing collected packages: httptools, cchardet, guardpost, rodi, aiofiles, essentials, blacksheep
Successfully installed aiofiles-0.4.0 blacksheep-0.2.2 cchardet-2.1.5 essentials-1.1.2 guardpost-0.0.5 httptools-0.1.1 rodi-1.0.8
```
, default example with error:
```
$ python3 start_001.py
  File "start_001.py", line 10
    return text(f'Hello, World! {datetime.utcnow().isoformat()}')
                                                               ^
SyntaxError: invalid syntax

```

**Comment by RobertoPrevato** [comment]
Hi @catafest,
it looks like you are using a version of Python that doesn't implement f strings.
f strings were added to [Python 3.6](https://www.python.org/dev/peps/pep-0498/).

BlackSheep is tested by the build pipelines with Python 3.7 and 3.8; some things might not work with older versions of the language. I could add 3.6 to the tests, right now I don't recall if this version is supported.
