### ISSUE TITLE
Unable to get any identifying information from a request

### ISSUE THREAD

**Issue by Izacht13** [RobertoPrevato/BlackSheep#36]
Trying to get some kind of identifying information from a blacksheep.request object.

Poking around in the source I found `request.identity` which is used for auth, but this is `NoneType` when trying to use it in a route.

Basically just some way to get the IP of the request is what I'm looking for.

**Comment by RobertoPrevato** [comment]
Hi @Izacht13 ,
Sorry for replying late.
You can read the client IP from the `request.scope`, that contains the scope handled by the underlying ASGI server.

For example:

```python
from blacksheep import Request
from blacksheep.server import Application
from blacksheep.server.responses import text


app = Application()


@app.route('/')
async def home(request: Request):
    # information like the client IP can be read from the scope
    # dictionary, populated by the ASGI server
    client_ip, client_port = request.scope.get('client')
    return text(f'client: {client_ip}:{client_port}')
```

The `request.identity` is populated when an authentication strategy is configured. For example, reading identity of a user from a JWT hearder, or a cookie. Unfortunately this part is not [documented yet, only mentioned](https://github.com/RobertoPrevato/BlackSheep/wiki/Authentication-and-authorization-strategies). In the last three months I didn't have much time to work on my framework, unfortunately. The project is alive but it's going slow now: these days I am working on a branch to remove `aiofles`, and built-in support for compression and decompression (Transfer-Encoding and Content-Encoding), made in an thoughtful way.

**Comment by Izacht13** [comment]
Hey, thanks for your help!
