### ISSUE TITLE
html() response method not exposed for contollers

### ISSUE THREAD

**Issue by skivis** [RobertoPrevato/BlackSheep#77]
At the moment the  Controller class exposes methods for all response types except html.

 Example:

```python
# We can do
return self.json({'Hello': 'World'})
return self.text('Hello, World')
return self.no_content()
# ...and so on

# But we can't do:
return self.html('...')
```

Not sure if this is intentional or not. :)

I'll submit a PR for this and you can have a look.

**Comment by RobertoPrevato** [comment]
Thanks! Indeed, this was something missing.
I just merged your PR, this change will be available in pypi soon, with the next release.
