### ISSUE TITLE
ASGI Support

### ISSUE THREAD

**Issue by pgjones** [RobertoPrevato/BlackSheep#8]
Congratulations, this looks to be a really cool project 👍 . 

I'd like to encourage you to adopt ASGI. (I see you discussed this in #7, but I wanted to add my voice of encouragement).

**Comment by RobertoPrevato** [comment]
Thanks, @pgjones,
I will look into this and try to adopt ASGI, or to add a way to integrate ASGI. So far I've been focused on architecture and other features, like built-in dependency injection for request handlers. One of the main drivers for not using ASGI was to avoid using `dict` and investigate the performance of a solution that relies more on custom extension types from Cython. Now I see that the performance is almost identical to the one of Uvicorn and Starlette, so my previous reasoning is falling. :) 

Thanks for your kind words and good advice.

**Comment by RobertoPrevato** [comment]
**For the record:**
I am planning the following:

* I will separate the HTTP server component from the web framework (the web framework will still be called "BlackSheep")
* While doing this, I will make BlackSheep ASGI compatible, so it will be possible to run it on top of `uvicorn`.
* my current HTTP server implementation will be published under a new name in a dedicated package

I recently explained the reasons why I didn't make BlackSheep ASGI compatible from the beginning, here: [https://robertoprevato.github.io/Presenting-BlackSheep/](https://robertoprevato.github.io/Presenting-BlackSheep/).

--
I will close this issue once support for ASGI will be complete

**Comment by pgjones** [comment]
Thanks for the update (including the well written post).

**Comment by RobertoPrevato** [comment]
Thanks, Phil - by the way I just realized I forgot to mention in my post that you also recommended the adoption of ASGI; I just updated my post.

**Comment by RobertoPrevato** [comment]
Done!

For now I tested only with #uvicorn, but it should work with #daphne and #hypercorn, too. I will dedicate time to prepare some good integration tests, as soon as possible.

**Comment by pgjones** [comment]
🎉 excellent.
